Help Weather:
  name: 帮天气
  entities:
    - sensor.helpweather_now_aqi
    - sensor.helpweather_now_humidity
    - sensor.helpweather_now_pm25
    - sensor.helpweather_now_prcp
    - sensor.helpweather_now_prcp24h
    - sensor.helpweather_now_stp
    - sensor.helpweather_now_temp
    - sensor.helpweather_now_tempf
    - sensor.helpweather_now_today
    - sensor.helpweather_now_uptime
    - sensor.helpweather_now_wd
    - sensor.helpweather_now_wden
    - sensor.helpweather_now_wdforce
    - sensor.helpweather_now_wdspd
    - sensor.helpweather_now_weather
    - sensor.helpweather_now_weatheren
    - sensor.helpweather_now_weatherimg
    - sensor.helpweather_now_wisib
    - sensor.helpweather_aqi
    - sensor.helpweather_aqi_co
    - sensor.helpweather_aqi_level
    - sensor.helpweather_aqi_no2
    - sensor.helpweather_aqi_o31h
    - sensor.helpweather_aqi_o38h
    - sensor.helpweather_aqi_pm10
    - sensor.helpweather_aqi_pm25
    - sensor.helpweather_aqi_so2
    - sensor.helpweather_aqi_update
    - sensor.helpweather_1hour_temp
    - sensor.helpweather_1hour_time
    - sensor.helpweather_1hour_weather
    - sensor.helpweather_3hour_temp
    - sensor.helpweather_3hour_time
    - sensor.helpweather_3hour_weather
    - sensor.helpweather_6hour_temp
    - sensor.helpweather_6hour_time
    - sensor.helpweather_6hour_weather
    - sensor.helpweather_9hour_temp
    - sensor.helpweather_9hour_time
    - sensor.helpweather_9hour_weather
    - sensor.helpweather_12hour_temp
    - sensor.helpweather_12hour_time
    - sensor.helpweather_12hour_weather
    - sensor.helpweather_15hour_temp
    - sensor.helpweather_15hour_time
    - sensor.helpweather_15hour_weather
    - sensor.helpweather_18hour_temp
    - sensor.helpweather_18hour_time
    - sensor.helpweather_18hour_weather
    - sensor.helpweather_21hour_temp
    - sensor.helpweather_21hour_time
    - sensor.helpweather_21hour_weather
    - sensor.helpweather_24hour_temp
    - sensor.helpweather_24hour_time
    - sensor.helpweather_24hour_weather
    - sensor.helpweather_27hour_temp
    - sensor.helpweather_27hour_time
    - sensor.helpweather_27hour_weather
    - sensor.helpweather_30hour_temp
    - sensor.helpweather_30hour_time
    - sensor.helpweather_30hour_weather
    - sensor.helpweather_today_date
    - sensor.helpweather_today_temphigh
    - sensor.helpweather_today_templow
    - sensor.helpweather_today_weather
    - sensor.helpweather_today_wind
    - sensor.helpweather_today_windforce
    - sensor.helpweather_tomorrowday_date
    - sensor.helpweather_tomorrowday_temphigh
    - sensor.helpweather_tomorrowday_templow
    - sensor.helpweather_tomorrowday_weather
    - sensor.helpweather_tomorrowday_wind
    - sensor.helpweather_tomorrowday_windforce
    - sensor.helpweather_oftertomorrowday_date
    - sensor.helpweather_oftertomorrowday_temphigh
    - sensor.helpweather_oftertomorrowday_templow
    - sensor.helpweather_oftertomorrowday_weather
    - sensor.helpweather_oftertomorrowday_wind
    - sensor.helpweather_oftertomorrowday_windforce
    - sensor.helpweather_zs_cl_suggestion_info
    - sensor.helpweather_zs_cl_suggestion_level
    - sensor.helpweather_zs_cl_suggestion_name
    - sensor.helpweather_zs_cl_suggestion_type
    - sensor.helpweather_zs_cy_suggestion_info
    - sensor.helpweather_zs_cy_suggestion_level
    - sensor.helpweather_zs_cy_suggestion_name
    - sensor.helpweather_zs_cy_suggestion_type
    - sensor.helpweather_zs_dy_suggestion_info
    - sensor.helpweather_zs_dy_suggestion_level
    - sensor.helpweather_zs_dy_suggestion_name
    - sensor.helpweather_zs_dy_suggestion_type
    - sensor.helpweather_zs_ffz_suggestion_info
    - sensor.helpweather_zs_ffz_suggestion_level
    - sensor.helpweather_zs_ffz_suggestion_name
    - sensor.helpweather_zs_ffz_suggestion_type
    - sensor.helpweather_zs_fh_suggestion_info
    - sensor.helpweather_zs_fh_suggestion_level
    - sensor.helpweather_zs_fh_suggestion_name
    - sensor.helpweather_zs_fh_suggestion_type
    - sensor.helpweather_zs_fs_suggestion_info
    - sensor.helpweather_zs_fs_suggestion_level
    - sensor.helpweather_zs_fs_suggestion_name
    - sensor.helpweather_zs_fs_suggestion_type
    - sensor.helpweather_zs_gj_suggestion_info
    - sensor.helpweather_zs_gj_suggestion_level
    - sensor.helpweather_zs_gj_suggestion_name
    - sensor.helpweather_zs_gj_suggestion_type
    - sensor.helpweather_zs_gm_suggestion_info
    - sensor.helpweather_zs_gm_suggestion_level
    - sensor.helpweather_zs_gm_suggestion_name
    - sensor.helpweather_zs_gm_suggestion_type
    - sensor.helpweather_zs_hc_suggestion_info
    - sensor.helpweather_zs_hc_suggestion_level
    - sensor.helpweather_zs_hc_suggestion_name
    - sensor.helpweather_zs_hc_suggestion_type
    - sensor.helpweather_zs_hz_suggestion_info
    - sensor.helpweather_zs_hz_suggestion_level
    - sensor.helpweather_zs_hz_suggestion_name
    - sensor.helpweather_zs_hz_suggestion_type
    - sensor.helpweather_zs_jt_suggestion_info
    - sensor.helpweather_zs_jt_suggestion_level
    - sensor.helpweather_zs_jt_suggestion_name
    - sensor.helpweather_zs_jt_suggestion_type
    - sensor.helpweather_zs_kqwr_suggestion_info
    - sensor.helpweather_zs_kqwr_suggestion_level
    - sensor.helpweather_zs_kqwr_suggestion_name
    - sensor.helpweather_zs_kqwr_suggestion_type
    - sensor.helpweather_zs_kt_suggestion_info
    - sensor.helpweather_zs_kt_suggestion_level
    - sensor.helpweather_zs_kt_suggestion_name
    - sensor.helpweather_zs_kt_suggestion_type
    - sensor.helpweather_zs_lk_suggestion_info
    - sensor.helpweather_zs_lk_suggestion_level
    - sensor.helpweather_zs_lk_suggestion_name
    - sensor.helpweather_zs_lk_suggestion_type
    - sensor.helpweather_zs_ls_suggestion_info
    - sensor.helpweather_zs_ls_suggestion_level
    - sensor.helpweather_zs_ls_suggestion_name
    - sensor.helpweather_zs_ls_suggestion_type
    - sensor.helpweather_zs_ly_suggestion_info
    - sensor.helpweather_zs_ly_suggestion_level
    - sensor.helpweather_zs_ly_suggestion_name
    - sensor.helpweather_zs_ly_suggestion_type
    - sensor.helpweather_zs_mf_suggestion_info
    - sensor.helpweather_zs_mf_suggestion_level
    - sensor.helpweather_zs_mf_suggestion_name
    - sensor.helpweather_zs_mf_suggestion_type
    - sensor.helpweather_zs_pj_suggestion_info
    - sensor.helpweather_zs_pj_suggestion_level
    - sensor.helpweather_zs_pj_suggestion_name
    - sensor.helpweather_zs_pj_suggestion_type
    - sensor.helpweather_zs_ssd_suggestion_info
    - sensor.helpweather_zs_ssd_suggestion_level
    - sensor.helpweather_zs_ssd_suggestion_name
    - sensor.helpweather_zs_ssd_suggestion_type
    - sensor.helpweather_zs_xc_suggestion_info
    - sensor.helpweather_zs_xc_suggestion_level
    - sensor.helpweather_zs_xc_suggestion_name
    - sensor.helpweather_zs_xc_suggestion_type
    - sensor.helpweather_zs_xq_suggestion_info
    - sensor.helpweather_zs_xq_suggestion_level
    - sensor.helpweather_zs_xq_suggestion_name
    - sensor.helpweather_zs_xq_suggestion_type
    - sensor.helpweather_zs_yd_suggestion_info
    - sensor.helpweather_zs_yd_suggestion_level
    - sensor.helpweather_zs_yd_suggestion_name
    - sensor.helpweather_zs_yd_suggestion_type
    - sensor.helpweather_zs_yh_suggestion_info
    - sensor.helpweather_zs_yh_suggestion_level
    - sensor.helpweather_zs_yh_suggestion_name
    - sensor.helpweather_zs_yh_suggestion_type
    - sensor.helpweather_zs_ys_suggestion_info
    - sensor.helpweather_zs_ys_suggestion_level
    - sensor.helpweather_zs_ys_suggestion_name
    - sensor.helpweather_zs_ys_suggestion_type
    - sensor.helpweather_zs_ysh_suggestion_info
    - sensor.helpweather_zs_ysh_suggestion_level
    - sensor.helpweather_zs_ysh_suggestion_name
    - sensor.helpweather_zs_ysh_suggestion_type
    - sensor.helpweather_zs_zs_suggestion_info
    - sensor.helpweather_zs_zs_suggestion_level
    - sensor.helpweather_zs_zs_suggestion_name
    - sensor.helpweather_zs_zs_suggestion_type
    - sensor.helpweather_zs_zwx_suggestion_info
    - sensor.helpweather_zs_zwx_suggestion_level
    - sensor.helpweather_zs_zwx_suggestion_name
    - sensor.helpweather_zs_zwx_suggestion_type
